mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: project.pickme

spring:
  application:
    name: pickme
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(y9y5JXo9A+cKB8Xi8nsRVLTzKEACOUB/O56oylGAqn6RWiKNAyQUnh6lF7xcG2QUCx+ee2WZj0RIQZZsiDanoTSamxSEoZ5cak4XGWD0EZUpnSl4MwYR3yFP3vLTiVIMyh3NXRfn1bs7GC/zCz2ijR/jhO+xDhCnOpt/7MdQ4SAYY3fR3koE8DJ7Kpj2KtUa)
    username: ENC(zo3xgo3TXMih7zIQ/wwSkg==)
    password: ENC(DvMAgRb3Z9VLlmqfrEESA/guiD7i2Oec)
  config:
    import:
      - "classpath:application-secret.yml"
      - "classpath:application-s3.yml"
  servlet:
    multipart:
      enabled: true
      max-request-size: 300MB
      max-file-size: 50MB
  mail:
    host: smtp.naver.com
    port: 465
    username: ENC(wWdiYL3v9NmkuW/UAyH9gT/8zcw4Us64nW6G8rJxTRk=)
    password: ENC(skQhPQvxBxXDvkF3QloiSw9JOqrjvFJJ)
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
      mail.smtp.starttls.enable: true

server:
  port: 8099
  servlet:
    session:
      timeout: 30m
