tracker:
  api:
    clientId: ENC(3dBsCnZpPcy321kKPLvMe6Qc4jjDzAUCEV+Lh7S9rV5G+rVblhqqFA==)
    clientSecret: ENC(JzcYeS/4NGvQXQJ2sLkM10jhexgmqy8epGh4Rgc39iNZKIPZvEOm1UwPAHDeK8rTByuY3k5IncrOekj9oREzUQ==)
